//
// Created by jiri on 1.3.23.
//

#ifndef FIRMWARE_PINDEFINITIONS_HPP
#define FIRMWARE_PINDEFINITIONS_HPP

#define INDOOR_SENSOR_PIN 12
#define OUTDOOR_SENSOR_PIN 13
#define WIFI_CONNECTED_PIN 14
#endif //FIRMWARE_PINDEFINITIONS_HPP
